>>> 'Pkg.add("MultiPoly")' log
INFO: Cloning cache of MultiPoly from https://github.com/daviddelaat/MultiPoly.jl.git
INFO: Installing DataStructures v0.3.13
INFO: Installing Docile v0.5.19
INFO: Installing MultiPoly v0.0.1
INFO: Package database updated

>>> 'Pkg.test("MultiPoly")' log
Julia Version 0.5.0-dev+1473
Commit 944dcbd (2015-11-25 19:05 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing MultiPoly
WARNING: module MultiPoly should explicitly import ^ from Base
Error During Test
  Test threw an exception of type ErrorException
  Expression: diff(p,:x,1) == 3.0 * x ^ 2 + 3.0 * y ^ 2
  factorial(3,2) has been moved to the package Combinatorics.jl.
  Run Pkg.add("Combinatorics") to install Combinatorics on Julia v0.5-
   in error at ./error.jl:21
   [inlined code] from combinatorics.jl:208
   in diff at /home/vagrant/.julia/v0.5/MultiPoly/src/mpolycalculus.jl:15
   in anonymous at test.jl:165
   in do_test at test.jl:186
   in include at ./boot.jl:260
   in include_from_node1 at ./loading.jl:392
   in include at ./boot.jl:260
   in include_from_node1 at ./loading.jl:392
   in process_options at ./client.jl:277
   in _start at ./client.jl:377
ERROR: LoadError: LoadError: There was an error during testing
 in record at test.jl:295
 [inlined code] from test.jl:100
 in do_test at test.jl:197
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 in process_options at ./client.jl:277
 in _start at ./client.jl:377
while loading /home/vagrant/.julia/v0.5/MultiPoly/test/mpolycalculus.jl, in expression starting on line 4
while loading /home/vagrant/.julia/v0.5/MultiPoly/test/runtests.jl, in expression starting on line 4
==============================[ ERROR: MultiPoly ]==============================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.5/MultiPoly/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Base.Pkg.PkgError("MultiPoly had test errors")
 [inlined code] from iostream.jl:207
 in __test#370__ at pkg/entry.jl:671
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:47
 in cd at pkg/dir.jl:31
 in test at pkg.jl:55
 in eval at ./boot.jl:263
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:254
 in _start at ./client.jl:377

>>> End of log
