>>> 'Pkg.add("MultiPoly")' log
INFO: Cloning cache of MultiPoly from https://github.com/daviddelaat/MultiPoly.jl.git
INFO: Installing DataStructures v0.4.2
INFO: Installing MultiPoly v0.0.1
INFO: Package database updated

>>> 'Pkg.test("MultiPoly")' log
Julia Version 0.5.0-dev+2335
Commit 5b1b0c5 (2016-01-28 04:34 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1
INFO: Testing MultiPoly
WARNING: module MultiPoly should explicitly import ^ from Base
Error During Test
  Test threw an exception of type ErrorException
  Expression: diff(p,:x,1) == 3.0 * x ^ 2 + 3.0 * y ^ 2
  factorial(3,2) has been moved to the package Combinatorics.jl.
  Run Pkg.add("Combinatorics") to install Combinatorics on Julia v0.5-
   in error at ./error.jl:21
   [inlined code] from ./combinatorics.jl:211
   in diff at /home/vagrant/.julia/v0.5/MultiPoly/src/mpolycalculus.jl:15
   in include at ./boot.jl:262
   in include_from_node1 at ./loading.jl:417
   in include at ./boot.jl:262
   in include_from_node1 at ./loading.jl:417
   in process_options at ./client.jl:245
   in _start at ./client.jl:301
ERROR: LoadError: LoadError: There was an error during testing
 in record at ./test.jl:317
 in do_test at ./test.jl:215
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:417
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:417
 in process_options at ./client.jl:245
 in _start at ./client.jl:301
while loading /home/vagrant/.julia/v0.5/MultiPoly/test/mpolycalculus.jl, in expression starting on line 4
while loading /home/vagrant/.julia/v0.5/MultiPoly/test/runtests.jl, in expression starting on line 4
==============================[ ERROR: MultiPoly ]==============================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.5/MultiPoly/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Base.Pkg.PkgError("MultiPoly had test errors")
 in test at ./pkg/entry.jl:671
 in anonymous at ./pkg/dir.jl:31
 in cd at ./file.jl:47
 in cd at ./pkg/dir.jl:31
 in test at ./pkg.jl:228
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:222
 in _start at ./client.jl:301

>>> End of log
