>>> 'Pkg.add("Orchestra")' log
INFO: Cloning cache of DecisionTree from git://github.com/bensadeghi/DecisionTree.jl.git
INFO: Cloning cache of DimensionalityReduction from git://github.com/JuliaStats/DimensionalityReduction.jl.git
INFO: Cloning cache of Orchestra from git://github.com/svs14/Orchestra.jl.git
INFO: Cloning cache of ScikitLearnBase from git://github.com/cstjean/ScikitLearnBase.jl.git
INFO: Installing ArrayViews v0.6.4
INFO: Installing BinDeps v0.4.5
INFO: Installing Conda v0.3.1
INFO: Installing DataArrays v0.3.8
INFO: Installing DataFrames v0.8.3
INFO: Installing DecisionTree v0.4.2
INFO: Installing DimensionalityReduction v0.1.1
INFO: Installing FactCheck v0.4.3
INFO: Installing FileIO v0.1.2
INFO: Installing GZip v0.2.20
INFO: Installing Iterators v0.1.10
INFO: Installing MLBase v0.5.3
INFO: Installing MacroTools v0.3.2
INFO: Installing Orchestra v0.0.5
INFO: Installing PyCall v1.7.2
INFO: Installing Reexport v0.0.3
INFO: Installing Rmath v0.1.3
INFO: Installing SHA v0.2.1
INFO: Installing ScikitLearnBase v0.1.1
INFO: Installing SortingAlgorithms v0.1.0
INFO: Installing StatsBase v0.9.0
INFO: Installing StatsFuns v0.3.1
INFO: Installing URIParser v0.1.6
INFO: Building Rmath
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Traceback (most recent call last):
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/bin/conda", line 4, in <module>
    import conda.cli
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/base/context.py", line 251, in <module>
    context = Context(SEARCH_PATH, conda, None)
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 692, in __init__
    self._add_search_path(search_path)
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 699, in _add_search_path
    return self._add_raw_data(load_file_configs(search_path))
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 346, in _file_yaml_loader
    assert fullpath.endswith(".yml") or fullpath.endswith("condarc"), fullpath
AssertionError: /home/vagrant/.julia/v0.4/Conda/deps/usr/condarc-julia
===============================[ ERROR: PyCall ]================================

LoadError: failed process: Process(setenv(`/home/vagrant/.julia/v0.4/Conda/deps/usr/bin/conda install -y numpy`,Union{ASCIIString,UTF8String}["PYTHON=","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/","PWD=/vagrant/0.4MZ","SHELL=/bin/bash","SSH_CONNECTION=10.0.2.2 51922 10.0.2.15 22","LD_LIBRARY_PATH=:/usr/local/lib/","CONDARC=/home/vagrant/.julia/v0.4/Conda/deps/usr/condarc-julia","MAIL=/var/mail/vagrant","LANG=en_US.UTF-8","SHLVL=3","LOGNAME=vagrant","XDG_RUNTIME_DIR=/run/user/1000","XDG_SESSION_ID=3","OLDPWD=/home/vagrant","SSH_CLIENT=10.0.2.2 51922 22","_=/usr/bin/timeout","USER=vagrant","TERM=vt100","HOME=/home/vagrant","OPENBLAS_MAIN_FREE=1","JAVA_HOME=/usr/lib/jvm/java-7-oracle","PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]
while loading /home/vagrant/.julia/v0.4/PyCall/deps/build.jl, in expression starting on line 17

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/vagrant/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

>>> 'Pkg.test("Orchestra")' log
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64
Memory: 2.4471054077148438 GB (808.76953125 MB free)
Uptime: 11528.0 sec
Load Avg:  0.79736328125  0.89013671875  0.96484375
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3500 MHz     505550 s        128 s      55178 s     458163 s         22 s
#2  3500 MHz     335526 s       5678 s      48793 s     712135 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.4
2 required packages:
 - JSON                          0.7.0
 - Orchestra                     0.0.5
23 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.4.5
 - Compat                        0.9.2
 - Conda                         0.3.1
 - DataArrays                    0.3.8
 - DataFrames                    0.8.3
 - DecisionTree                  0.4.2
 - DimensionalityReduction       0.1.1
 - FactCheck                     0.4.3
 - FileIO                        0.1.2
 - GZip                          0.2.20
 - Iterators                     0.1.10
 - MLBase                        0.5.3
 - MacroTools                    0.3.2
 - PyCall                        1.7.2
 - Reexport                      0.0.3
 - Rmath                         0.1.3
 - SHA                           0.2.1
 - ScikitLearnBase               0.1.1
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.9.0
 - StatsFuns                     0.3.1
 - URIParser                     0.1.6
INFO: Testing Orchestra
ERROR: LoadError: LoadError: PyCall not properly installed. Please run Pkg.build("PyCall")
 [inlined code] from /home/vagrant/.julia/v0.4/PyCall/src/startup.jl:45
 in anonymous at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/PyCall/src/startup.jl, in expression starting on line 42
while loading /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl, in expression starting on line 37
ERROR: LoadError: LoadError: LoadError: Failed to precompile PyCall to /home/vagrant/.julia/lib/v0.4/PyCall.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:266
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in require at ./loading.jl:259
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/Orchestra/src/system.jl, in expression starting on line 4
while loading /home/vagrant/.julia/v0.4/Orchestra/src/Orchestra.jl, in expression starting on line 5
while loading /home/vagrant/.julia/v0.4/Orchestra/test/runtests.jl, in expression starting on line 4
==============================[ ERROR: Orchestra ]==============================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/Orchestra/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Orchestra had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
