>>> 'Pkg.add("Qwt")' log
INFO: Cloning cache of ImmutableArrays from https://github.com/JuliaGeometry/ImmutableArrays.jl.git
INFO: Cloning cache of Qwt from https://github.com/tbreloff/Qwt.jl.git
INFO: Installing BinDeps v0.4.2
INFO: Installing ColorTypes v0.2.6
INFO: Installing Colors v0.6.6
INFO: Installing Conda v0.2.3
INFO: Installing FixedPointNumbers v0.1.4
INFO: Installing ImmutableArrays v0.0.12
INFO: Installing MacroTools v0.3.2
INFO: Installing PyCall v1.7.1
INFO: Installing Qwt v0.0.1
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.2.1
INFO: Installing URIParser v0.1.6
INFO: Building PyCall
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.5/SHA.ji for module SHA.
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.5/BinDeps.ji for module BinDeps.
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.5/Conda.ji for module Conda.
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata .....Error: HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/pro/linux-64/repodata.json.bz2: https://repo.continuum.io/pkgs/pro/linux-64/

===============================[ ERROR: PyCall ]================================

LoadError: failed process: Process(setenv(`/home/vagrant/.julia/v0.5/Conda/deps/usr/bin/conda install -y numpy`,String["PYTHON=","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/","PWD=/vagrant/0.5MZ","SHELL=/bin/bash","SSH_CONNECTION=10.0.2.2 50677 10.0.2.15 22","LD_LIBRARY_PATH=:/usr/local/lib/","CONDARC=/home/vagrant/.julia/v0.5/Conda/deps/usr/condarc-julia","MAIL=/var/mail/vagrant","LANG=en_US.UTF-8","SHLVL=3","LOGNAME=vagrant","XDG_RUNTIME_DIR=/run/user/1000","XDG_SESSION_ID=3","OLDPWD=/home/vagrant","SSH_CLIENT=10.0.2.2 50677 22","_=/usr/bin/timeout","USER=vagrant","TERM=vt100","HOME=/home/vagrant","OPENBLAS_MAIN_FREE=1","JAVA_HOME=/usr/lib/jvm/java-7-oracle","PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]
while loading /home/vagrant/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/vagrant/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of Qwt
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("Qwt")' log
Julia Version 0.5.0-rc2+0
Commit 0350e57 (2016-08-12 11:25 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-93-generic #140-Ubuntu SMP Mon Jul 18 21:21:05 UTC 2016 x86_64 x86_64
Memory: 2.4471054077148438 GB (700.6796875 MB free)
Uptime: 17351.0 sec
Load Avg:  0.9404296875  0.93115234375  0.7568359375
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3499 MHz     860230 s        932 s     101662 s     546514 s         41 s
#2  3499 MHz     249933 s       6368 s      48550 s    1375534 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.5
2 required packages:
 - JSON                          0.6.0
 - Qwt                           0.0.1
12 additional packages:
 - BinDeps                       0.4.2
 - ColorTypes                    0.2.6
 - Colors                        0.6.6
 - Compat                        0.8.7
 - Conda                         0.2.3
 - FixedPointNumbers             0.1.4
 - ImmutableArrays               0.0.12
 - MacroTools                    0.3.2
 - PyCall                        1.7.1
 - Reexport                      0.0.3
 - SHA                           0.2.1
 - URIParser                     0.1.6
INFO: Testing Qwt
ERROR: LoadError: LoadError: PyCall not properly installed. Please run Pkg.build("PyCall")
 in macro expansion; at /home/vagrant/.julia/v0.5/PyCall/src/startup.jl:45 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/vagrant/.julia/v0.5/PyCall/src/startup.jl, in expression starting on line 42
while loading /home/vagrant/.julia/v0.5/PyCall/src/PyCall.jl, in expression starting on line 37
ERROR: LoadError: Failed to precompile PyCall to /home/vagrant/.julia/lib/v0.5/PyCall.ji
 in compilecache(::String) at ./loading.jl:505
 in require(::Symbol) at ./loading.jl:337
 in include_from_node1(::String) at ./loading.jl:426
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/vagrant/.julia/v0.5/Qwt/src/Qwt.jl, in expression starting on line 148
ERROR: LoadError: Failed to precompile Qwt to /home/vagrant/.julia/lib/v0.5/Qwt.ji
 in compilecache(::String) at ./loading.jl:505
 in require(::Symbol) at ./loading.jl:364
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/vagrant/.julia/v0.5/Qwt/test/runtests.jl, in expression starting on line 1
=================================[ ERROR: Qwt ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.5/Qwt/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Qwt had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318

>>> End of log
