>>> 'Pkg.add("Robotlib")' log
INFO: Cloning cache of Robotlib from git://github.com/baggepinnen/Robotlib.jl.git
INFO: Installing ArrayViews v0.6.4
INFO: Installing BinDeps v0.3.21
INFO: Installing Blosc v0.1.4
INFO: Installing ColorTypes v0.2.1
INFO: Installing Colors v0.6.3
INFO: Installing Conda v0.1.9
INFO: Installing DataArrays v0.2.20
INFO: Installing DataFrames v0.6.10
INFO: Installing Dates v0.4.4
INFO: Installing Docile v0.5.23
INFO: Installing FixedPointNumbers v0.1.2
INFO: Installing GZip v0.2.18
INFO: Installing HDF5 v0.5.8
INFO: Installing LaTeXStrings v0.1.6
INFO: Installing MAT v0.2.14
INFO: Installing MacroTools v0.3.0
INFO: Installing Plots v0.5.2
INFO: Installing PyCall v1.4.0
INFO: Installing PyPlot v2.1.1
INFO: Installing Quaternions v0.1.0
INFO: Installing Reexport v0.0.3
INFO: Installing Requires v0.2.2
INFO: Installing Robotlib v0.0.1
INFO: Installing SHA v0.1.2
INFO: Installing SortingAlgorithms v0.0.6
INFO: Installing StatsBase v0.7.4
INFO: Installing StatsFuns v0.2.0
INFO: Installing URIParser v0.1.2
INFO: Installing Zlib v0.1.12
INFO: Building Blosc
INFO: Building HDF5
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Fetching package metadata: ....
Solving package specifications: .................
# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.10.4                   py27_0    http://repo.continuum.io/pkgs/free/linux-64/numpy-1.10.4-py27_0.tar.bz2
INFO: PyCall is using /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.11) at /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7.so
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of Robotlib
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("Robotlib")' log
Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing Robotlib
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/PyCall.ji for module PyCall.
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/PyPlot.ji for module PyPlot.
WARNING: No working GUI backend found for matplotlib.
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/HDF5.ji for module HDF5.
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/MAT.ji for module MAT.
ERROR: LoadError: LoadError: LoadError: ArgumentError: Debug not found in path
 in require at loading.jl:233
 [inlined code] from /home/vagrant/.julia/v0.4/Requires/src/require.jl:11
 in require at /home/vagrant/.julia/v0.4/Requires/src/hook.jl:17
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/Robotlib/src/calibLPOE.jl, in expression starting on line 184
while loading /home/vagrant/.julia/v0.4/Robotlib/src/Robotlib.jl, in expression starting on line 37
while loading /home/vagrant/.julia/v0.4/Robotlib/test/runtests.jl, in expression starting on line 3
==============================[ ERROR: Robotlib ]===============================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/Robotlib/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Robotlib had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
