>>> 'Pkg.add("SGP4")' log
INFO: Cloning cache of SGP4 from git://github.com/crbinz/SGP4.jl.git
INFO: Installing BinDeps v0.3.18
INFO: Installing Conda v0.1.7
INFO: Installing Dates v0.4.4
INFO: Installing HttpCommon v0.2.4
INFO: Installing PyCall v1.1.2
INFO: Installing SGP4 v0.0.2
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.0
INFO: Building PyCall
INFO: PyCall is using /usr/bin/python (Python 2.7.6) at /usr/bin/python, libpython = libpython2.7
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of SGP4
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("SGP4")' log
Julia Version 0.4.0-rc3
Commit 483d548* (2015-09-27 20:34 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
INFO: Testing SGP4
INFO: Recompiling stale cache file /home/vagrant/.julia/lib/v0.4/PyCall.ji for module PyCall.
WARNING: requiring "Dates" in module "SGP4" did not define a corresponding module.
ERROR: LoadError: LoadError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named sgp4.io',)

 [inlined code] from /home/vagrant/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:79
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/vagrant/.julia/v0.4/SGP4/src/SGP4.jl, in expression starting on line 360
while loading /home/vagrant/.julia/v0.4/SGP4/test/runtests.jl, in expression starting on line 1
================================[ ERROR: SGP4 ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/SGP4/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: SGP4 had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:753
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:284
 in _start at ./client.jl:411

>>> End of log
