>>> 'Pkg.add("YT")' log
INFO: Cloning cache of YT from git://github.com/jzuhone/YT.jl.git
INFO: Installing BinDeps v0.3.21
INFO: Installing ColorTypes v0.1.7
INFO: Installing Colors v0.5.4
INFO: Installing Conda v0.2.3
INFO: Installing Docile v0.5.23
INFO: Installing FixedPointNumbers v0.0.12
INFO: Installing HttpCommon v0.1.2
INFO: Installing LaTeXStrings v0.1.6
INFO: Installing MacroTools v0.2.0
INFO: Installing Plots v0.4.2
INFO: Installing PyCall v1.2.0
INFO: Installing PyPlot v2.1.1
INFO: Installing Reexport v0.0.3
INFO: Installing Requires v0.2.0
INFO: Installing SHA v0.2.1
INFO: Installing SymPy v0.2.40
INFO: Installing URIParser v0.0.7
INFO: Installing YT v0.2.0
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `'' -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: no such file or directory (ENOENT)
using the Python distribution in the Conda package
Traceback (most recent call last):
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/bin/conda", line 4, in <module>
    import conda.cli
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/base/context.py", line 252, in <module>
    context = Context(SEARCH_PATH, conda, None)
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 692, in __init__
    self._add_search_path(search_path)
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 699, in _add_search_path
    return self._add_raw_data(load_file_configs(search_path))
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/home/vagrant/.julia/v0.3/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 346, in _file_yaml_loader
    assert fullpath.endswith(".yml") or fullpath.endswith("condarc"), fullpath
AssertionError: /home/vagrant/.julia/v0.3/Conda/deps/usr/condarc-julia
===============================[ ERROR: PyCall ]================================

failed process: Process(setenv(`/home/vagrant/.julia/v0.3/Conda/deps/usr/bin/conda install -y numpy`,Union(UTF8String,ASCIIString)["PYTHON=","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/","PWD=/vagrant/0.3MZ","SHELL=/bin/bash","SSH_CONNECTION=10.0.2.2 54334 10.0.2.15 22","LD_LIBRARY_PATH=:/usr/local/lib/","CONDARC=/home/vagrant/.julia/v0.3/Conda/deps/usr/condarc-julia","MAIL=/var/mail/vagrant","LANG=en_US.UTF-8","SHLVL=3","LOGNAME=vagrant","XDG_RUNTIME_DIR=/run/user/1000","XDG_SESSION_ID=3","OLDPWD=/home/vagrant","SSH_CLIENT=10.0.2.2 54334 22","_=/usr/bin/timeout","USER=vagrant","TERM=vt100","HOME=/home/vagrant","JAVA_HOME=/usr/lib/jvm/java-7-oracle","PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]
while loading /home/vagrant/.julia/v0.3/PyCall/deps/build.jl, in expression starting on line 17

================================================================================
INFO: Building YT
=================================[ ERROR: YT ]==================================

PyCall not properly installed. Please run Pkg.build("PyCall")
while loading /home/vagrant/.julia/v0.3/PyCall/src/PyCall.jl, in expression starting on line 36
while loading /home/vagrant/.julia/v0.3/YT/deps/yt_check.jl, in expression starting on line 1
while loading /home/vagrant/.julia/v0.3/YT/deps/build.jl, in expression starting on line 1

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: YT and PyCall had build errors.

 - packages with build errors remain installed in /home/vagrant/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("YT", "PyCall")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

>>> 'Pkg.test("YT")' log
Package was unable to be tested.
>>> End of log
